---
- hosts: local
  connection: local
  become: true
  tasks:
      - name: Run update
        apt:
            upgrade: yes
            update_cache: true
      - name: Install 
        apt:
            name: htop
